title: Colabois

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-zopfli
  - jekyll-liquify
  - jekyll-seo-tag

exclude:
  - README.md
  - Makefile
  - Dockerfile
  - Jenkinsfile
  - .jekyll-cache

collections:
  posts:
    output: true
    permalink: /blog/:title
  pages:
    output: true
    permalink: /:title

defaults:
  - scope:
      type: posts
    values:
      layout: post

permalink: /:title

languages: ["en", "fr", "it", "es", "eo"]
exclude_from_localizations: ["assets", "favicon.ico"]
default_locale_in_subfolder: true
language_redirections: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]

baseurl: ""
