plugins:
    - jekyll-autoprefixer

exclude:
    - README.md
    - Makefile

defaults:
    - scope:
        path: _posts
      values:
        layout: post

sass:
    style: compressed

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    ignore:
        envs: [local]
    blanklines: false
    startings: [html, head, body]