plugins:
  - jekyll-commonmark
  - jekyll-polyglot
  - jekyll-autoprefixer

exclude:
  - README.md
  - Makefile
  - Dockerfile
  - Jenkinsfile
  - .jekyll-cache

collections_dir: collections

collections:
  posts:
    output: true
  pages:
    output: true
    permalink: /:title

permalink: /:title

languages: ["en", "fr", "es", "eo"]
default_lang: "redirect"
exclude_from_localization: ["css", "fonts", "img"]
parallel_localization: true

defaults:
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: pages
    values:
      permalink: /:title

markdown: CommonMark
commonmark:
  extensions: ["strikethrough", "autolink", "table"]

sass:
  style: compressed
  sourcemap: never

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]
