plugins:
    - jekyll-autoprefixer
    - jekyll-polyglot

exclude:
    - README.md
    - Makefile
    - Dockerfile
    - Jenkinsfile

collections:
    posts:
        output: true
    pages:
        output: true
        permalink: /:title

permalink: /:title

languages: ["en", "fr", "es"]
default_lang: "en"
exclude_from_localization: ["css", "fonts", "img"]
parallel_localization: true

defaults:
    - scope:
        path: _posts
      values:
        layout: post
    - scope:
        path: pages
      values:
        permalink: /:title

sass:
    style: compressed
    sourcemap: never

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    ignore:
        envs: [local]
    blanklines: false
    startings: [html, head, body]
