plugins:
    - jekyll-autoprefixer

exclude:
    - README.md
    - Makefile
    - Dockerfile
    - Jenkinsfile
    
collections_dir: collections

collections:
    en:
        output: true
        permalink: /en/:name
    fr:
        output: true
        permalink: /fr/:name
    es:
        output: true
        permalink: /es/:name

defaults:
    - scope:
        path: _posts
      values:
        layout: post

sass:
    style: compressed

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    ignore:
        envs: [local]
    blanklines: false
    startings: [html, head, body]
