plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-zopfli

exclude:
  - README.md
  - Makefile
  - Dockerfile
  - Jenkinsfile
  - .jekyll-cache

collections:
  pages:
    output: true
    permalink: /:title

permalink: /:title

languages: ["en", "fr", "es", "eo"]
exclude_from_localizations: ["assets", "favicon.ico"]

kramdown:
  parse_block_html: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]
