plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-zopfli
  - jekyll-toc

exclude:
  - README.md
  - Makefile
  - Dockerfile
  - Jenkinsfile
  - .jekyll-cache

collections:
  posts:
    output: true
    permalink: /posts/:title
  pages:
    output: true
    permalink: /:title

permalink: /:title

defaults:
  - scope:
      path: redirect
    values:
      permalink: /

languages: ["en", "fr", "es", "eo"]
exclude_from_localizations: ["assets", "favicon.ico"]
default_locale_in_subfolder: true

markdown: CommonMark
commonmark:
  extensions: ["strikethrough", "autolink", "table"]

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]
