plugins:
    - jekyll-autoprefixer

exclude:
    - README.md
    - Makefile
    - Dockerfile
    - Jenkinsfile

languages: ["en", "fr", "es"]
default_lang: "en"
exclude_from_localization: ["css", "fonts", "img"]
parallel_localization: true

defaults:
    - scope:
        path: _posts
      values:
        layout: post

sass:
    style: compressed
    sourcemap: never

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    ignore:
        envs: [local]
    blanklines: false
    startings: [html, head, body]
