plugins:
    - jekyll-autoprefixer

exclude:
    - README.md
    - Makefile

defaults:
    - scope: 
        path: img/favicon.ico
      values:
        permalink: /favicon.ico

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    ignore:
        envs: [local]
    blanklines: false
    startings: [html, head, body]